### ISSUE TITLE
Add new features for manipulating with to-do items

### ISSUE THREAD

**Issue by Alice-Rez** [Alice-Rez/Not-to-forget#1]
Add additional features to current version:

- [x] make possible to edit item (individual parts of it)

- [x] make possible to delete item

- [x] make possible to check finished to-dos
